### ISSUE TITLE
Proper way to create card with CustomFields

### ISSUE THREAD

**Issue by agustinscaz** [gregsdennis/Manatee.Trello#101] opened 2017-09-07 12:12 UTC
Hi, 

Can you explain me how is the proper way to create a Card with CustomFields?

This is the code i have:

```
private static void CreateCard(Board board, Task dbTask)
{
    var list = board.Lists[0];
    card card = new Card(dbTask.Name);
    card.Cards.Add(card);
    card.Name = dbTask.Name;
    card.Description = "Lorem Ipsum";
    card.DueDate = DateTime.Now;
}
```

Thanks in advance!

**Comment by gregsdennis** [comment] 2017-09-07 18:42
I think there's something wrong with your snippet. The `Card` class doesn't have a `Cards` property.  I think you mean to have `list` there.

Also, the `Card` constructor requires an ID of an existing card, not a name. It doesn't generate a new card, it merely creates an instance to represent the card.

The `List.Cards.Add(Card)` method is for adding a duplicate of an already-created card. To create a new card, you want to use the overload that allows you to pass in the card properties. This will return the `Card` instance representing the card in Trello.

You want this

    var list = board.Lists[0];
    var card = list.Cards.Add(dbTask.Name, description: "Lorem Ipsum", dueDate: DateTime.Now);

I'm not sure how you're using CustomFields, but from what I can tell, it doesn't factor in here.

Please read the Usage page in the wiki and the method descriptions provides in the code (which you can find in the tool tips in your IDE).

**Comment by agustinscaz** [comment] 2017-09-08 06:02
Hi @gregsdennis ,

Actually the code is like you say, and that works to create a card, but what I don't know how to add the CustomFields.
I have created two custom fields created in Trello
ID (integer)
Name (string)

But when I try to create a card with them, I don't find any method to set (write).

Can you show me an example of code to write the CustomFields?

Thanks!

**Comment by gregsdennis** [comment] 2017-09-08 07:40
I assume you have the Manatee.Trello.CustomFields library installed.

You need to use the `.CustomFields()` extension method on a card.  This will return a `CustomFieldData` collection.  Each field declares its name, the value, and the value's type.

    var fields = card.CustomFields();
    foreach(var field in fields)
    {
        ...
    }

**Comment by agustinscaz** [comment] 2017-09-08 07:44
Yes, that will return a CustomFieldData, but... how can I **set** the parameters I want there?

**Comment by gregsdennis** [comment] 2017-09-08 08:00
Unfortunately, Trello hasn't exposed a way to set plug-in data through the API, only to enable/disable them on a board.  That limits this library to read only functionality.

**Comment by agustinscaz** [comment] 2017-09-08 08:00
That's my problem... so there's no solution to write the CustomFields.

Thanks :)

**Comment by gregsdennis** [comment] 2017-09-08 08:03
I'll do some exploration to see if I can reverse-engineer the plugin itself to try to find out how it sets the data.

**Comment by agustinscaz** [comment] 2017-09-08 08:58
Wow! that would be great!!

Thanks!

**Comment by gregsdennis** [comment] 2017-09-26 00:14
**UPDATE**

I captured a few tests with Fiddler and found that they're setting an `X-Trello-RefId` header with a value that I don't have access to.  The kicker is that it changes with every call, and I can't find where the website is pulling it from.

**Comment by gregsdennis** [comment] 2017-09-27 01:49
Nicely canned response from the Trello dev team:

>Thanks for writing to us!
>
>We understand that this is something many users would find helpful, and our platform team has this on their list to look into in the future. I'll pass your interest in this along to the team as they continue to consider this.
>
>Please let us know if there’s anything else we can help you with, and have a great rest of your day!

**Closed** 2017-10-03 19:13 UTC
Labels: question
