### ISSUE TITLE
The update event does not work

### ISSUE THREAD

**Issue by duhovich** [gregsdennis/Manatee.Trello#218] opened 2018-05-17 14:37 UTC
I use Manatee.Trello to process webhook on AspNetMvc5.
I created a class TrelloConfig:
![code_screen_1](https://user-images.githubusercontent.com/22120606/40184138-252f8b8e-59f8-11e8-9ba9-559a918f5145.png)
I call the method in Application_Start(Global.asax.cs):
Application["Board"] = TrelloConfig.Init();
Then I pass the webhook's body to the processor in webapi controller:
TrelloProcessor.ProcessNotification(body);
And deploy it on AppHarbor. But the event does not trigger and the log is not written.
Manatee trello from Nuget,version 3.0.10

**Comment by gregsdennis** [comment] 2018-05-17 18:33
I'll have a look. Thanks for reporting this.

**Comment by gregsdennis** [comment] 2018-05-18 04:34
I've reached down the issue. The event was only firing after a refresh call, which seems rather redundant.  I've fixed this to fire any time new data is merged in.

You can expect an update soon. Look for v3.0.11.

**Comment by duhovich** [comment] 2018-05-18 12:01
Thanks, now works. But how can I see what changes have occurred? The second parameter returns only the string "Organizational", regardless of what changes occurred.

**Comment by gregsdennis** [comment] 2018-05-19 01:28
Yeah, I found a deeper issue with this. I'm working on it now.  Sorry for the inconvenience.

**Comment by gregsdennis** [comment] 2018-05-20 23:57
So the problem is a change that I made with 3.0.0. In previous versions, I had specified that the entities used by actions and notifications should not be the primary, cached entities since the actions generally contained data that was *intended* to be out of date. When I was updating the code for v3.0.0, I had forgotten this, so in my zeal to use every bit of data that came through, I changed actions and notifications to update the cached entities.

Now I see error of my assumption, and I need to revert back to the dummy instances for actions and notifications.  It's not difficult; it just takes a while.

**Comment by gregsdennis** [comment] 2018-05-21 20:42
I have a couple branches trying to apply two approaches.

1. **bug/218-dont-update-actions-notifications** - Adds an additional parameter (seemingly everywhere) that indicates whether that instance should allow syncing.
2. **bug/218-using-null-auth** - Same concept, but uses a new internal static auth object as the indicator.

The idea is that entities for actions and notifications should be static snapshots, not live, updating entities.  Other ideas I've had:

3. Add a whole new slew of classes that are intended to represent the entities specifically as snapshots.  They would implement the existing entity interfaces and replace the current entities on ActionData and NotificationData.
4. Just expose the `IJson*` instances (as the interfaces) on a new property and obsolete (and disconnect) the existing `Data` property.

I rather like \#4 as it's likely the simplest.

I'm going to post this in Slack as well to see if anyone there (of all three people who have joined so far) have a preference.

**Closed** 2018-05-29 12:56 UTC
Labels: bug, replicated
